### ISSUE TITLE
How to approach localization?

### ISSUE THREAD

**Issue by mezka** [samber/invoice-as-a-service#46]
@samber can you make an skeleton to support translation/localization of the Invoice template?

I need to make Spanish translation, I can make small changes but do not really have the skills to make the generalization for upstream.

**Comment by samber** [comment]
Unfortunately, I'm a bit busy currently.

I can guide you to the laravel documentation -> https://laravel.com/docs/6.x/localization

But if you want me to prioritize this feature shortly, please sponsor my projects ! https://github.com/sponsors/samber/

Sorry for that.

**Comment by mezka** [comment]
#47
